version: '3.8'
services:
  article_search_app:
    build: .
    ports:
      - "9997:9997"
    volumes:
      - .:/app
    environment:
      # 图片上传服务器地址，参考https://github.com/fucheng830/image_store自行部署
      - IMAGE_SERVER=https://static.123qiming.com